apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bucket98/backend:system-v1
        env:
        - name: KAFKA_HOST
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: kafka_host.txt
        - name: CLOUD_USER
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud_user.txt
        - name: CLOUD_PASSWD
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud_passwd.txt
        ports:
        - containerPort: 8080
