global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'actuator'
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["backend-internal-1.backend:8080", "backend-internal-2.backend:8080", "backend-internal-3.backend:8080"]
